-- Add 50 hotels for each major location

-- TOKYO, JAPAN (50 hotels)
INSERT INTO hotels (name, description, address, city, country, star_rating, price_per_night, main_image, amenities) VALUES
('Shinjuku Grand Hotel', 'Modern luxury in the heart of Shinjuku with stunning city views.', '2-1-1 Nishi-Shinjuku', 'Tokyo', 'Japan', 5, 480.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Free WiFi', 'Gym', 'Concierge']),
('Shibuya Crossing Hotel', 'Contemporary hotel overlooking the famous Shibuya Crossing.', '1-12-3 Shibuya', 'Tokyo', 'Japan', 4, 320.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'City View']),
('Ginza Palace Hotel', 'Elegant accommodations in Tokyo''s premier shopping district.', '5-8-1 Ginza', 'Tokyo', 'Japan', 5, 550.00, '/placeholder.svg?height=400&width=600', ARRAY['Spa', 'Restaurant', 'Bar', 'Free WiFi', 'Concierge', 'Room Service']),
('Asakusa Traditional Inn', 'Experience authentic Japanese hospitality near Senso-ji Temple.', '2-3-5 Asakusa', 'Tokyo', 'Japan', 3, 150.00, '/placeholder.svg?height=400&width=600', ARRAY['Japanese Breakfast', 'Free WiFi', 'Garden']),
('Roppongi Hills Hotel', 'Sophisticated urban retreat in the entertainment district.', '6-10-1 Roppongi', 'Tokyo', 'Japan', 5, 620.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Free WiFi']),
('Tokyo Station Hotel', 'Historic hotel within the iconic Tokyo Station building.', '1-9-1 Marunouchi', 'Tokyo', 'Japan', 5, 490.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Spa', 'Free WiFi', 'Concierge']),
('Ueno Park Hotel', 'Comfortable stay near museums and Ueno Park.', '4-5-1 Ueno', 'Tokyo', 'Japan', 3, 120.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Restaurant', 'Parking']),
('Odaiba Seaside Resort', 'Waterfront hotel with Rainbow Bridge views.', '1-9-1 Daiba', 'Tokyo', 'Japan', 4, 280.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Restaurant', 'Sea View', 'Free WiFi', 'Gym']),
('Akihabara Tech Hotel', 'Modern capsule-style hotel in Electric Town.', '1-15-9 Akihabara', 'Tokyo', 'Japan', 3, 80.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Vending Machines', '24h Reception']),
('Harajuku Fashion Hotel', 'Trendy boutique hotel near Takeshita Street.', '1-20-1 Jingumae', 'Tokyo', 'Japan', 4, 250.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Design Interior']),
('Imperial Tokyo Hotel', 'Legendary hotel with over a century of hospitality excellence.', '1-1-1 Uchisaiwaicho', 'Tokyo', 'Japan', 5, 700.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Multiple Restaurants', 'Bar', 'Gym', 'Concierge']),
('Ikebukuro Business Hotel', 'Convenient location for business travelers.', '3-28-13 Nishi-Ikebukuro', 'Tokyo', 'Japan', 3, 110.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Business Center', 'Restaurant']),
('Meguro Garden Hotel', 'Peaceful retreat in a residential neighborhood.', '2-16-11 Meguro', 'Tokyo', 'Japan', 4, 220.00, '/placeholder.svg?height=400&width=600', ARRAY['Garden', 'Restaurant', 'Free WiFi', 'Parking']),
('Ebisu Wine Hotel', 'Boutique hotel with excellent wine selection.', '1-5-8 Ebisu', 'Tokyo', 'Japan', 4, 290.00, '/placeholder.svg?height=400&width=600', ARRAY['Wine Bar', 'Restaurant', 'Free WiFi', 'Room Service']),
('Nakano Arts Hotel', 'Creative hotel near anime and manga shops.', '5-52-15 Nakano', 'Tokyo', 'Japan', 3, 95.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Cafe', 'Art Gallery']),
('Shinagawa Business Tower', 'High-rise hotel with excellent transit access.', '4-10-30 Takanawa', 'Tokyo', 'Japan', 4, 260.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Gym', 'Free WiFi', 'Business Center']),
('Kagurazaka Boutique Inn', 'Charming hotel in Tokyo''s French quarter.', '3-2-1 Kagurazaka', 'Tokyo', 'Japan', 4, 240.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Garden', 'Tea Room']),
('Sumida River Hotel', 'Riverside hotel with Sky Tree views.', '1-23-20 Yokoami', 'Tokyo', 'Japan', 4, 270.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'River View', 'Free WiFi']),
('Nihonbashi Heritage Hotel', 'Classic hotel in Tokyo''s historic merchant district.', '2-10-4 Nihonbashi', 'Tokyo', 'Japan', 4, 310.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Concierge']),
('Tsukiji Market Hotel', 'Perfect base for food lovers near the outer market.', '4-7-5 Tsukiji', 'Tokyo', 'Japan', 3, 140.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Restaurant', 'Market Tours']),
('Tokyo Bay View Hotel', 'Panoramic bay views and resort amenities.', '2-6-1 Kaigan', 'Tokyo', 'Japan', 5, 450.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Bay View', 'Gym', 'Free WiFi']),
('Yoyogi Park Hotel', 'Nature-adjacent hotel near Meiji Shrine.', '1-2-20 Yoyogi', 'Tokyo', 'Japan', 4, 230.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Garden', 'Free WiFi', 'Bike Rental']),
('Gotanda City Hotel', 'Affordable comfort in a local neighborhood.', '1-3-10 Higashi-Gotanda', 'Tokyo', 'Japan', 3, 100.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Restaurant', 'Laundry']),
('Azabu Luxury Residence', 'Exclusive apartment-style hotel for extended stays.', '2-3-10 Azabu-Juban', 'Tokyo', 'Japan', 5, 580.00, '/placeholder.svg?height=400&width=600', ARRAY['Kitchen', 'Concierge', 'Gym', 'Free WiFi', 'Room Service']),
('Otemachi Tower Hotel', 'Ultra-modern hotel in the business district.', '1-5-1 Otemachi', 'Tokyo', 'Japan', 5, 520.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Free WiFi']),
('Yanaka Traditional House', 'Stay in a renovated traditional townhouse.', '3-11-15 Yanaka', 'Tokyo', 'Japan', 3, 130.00, '/placeholder.svg?height=400&width=600', ARRAY['Japanese Garden', 'Free WiFi', 'Tea Ceremony']),
('Toyosu Market Hotel', 'Modern hotel near the new fish market.', '6-6-1 Toyosu', 'Tokyo', 'Japan', 4, 210.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Market Access']),
('Daikanyama Design Hotel', 'Stylish boutique hotel in hip Daikanyama.', '13-3 Sarugakucho', 'Tokyo', 'Japan', 4, 300.00, '/placeholder.svg?height=400&width=600', ARRAY['Cafe', 'Bar', 'Free WiFi', 'Design Interior']),
('Korakuen Dome Hotel', 'Sports and entertainment complex hotel.', '1-3-61 Koraku', 'Tokyo', 'Japan', 4, 240.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Spa', 'Free WiFi']),
('Monzen-Nakacho Inn', 'Traditional neighborhood charm with modern comforts.', '1-14-1 Tomioka', 'Tokyo', 'Japan', 3, 115.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Restaurant', 'Temple Tours']),
('Shimokitazawa Music Hotel', 'Artistic hotel in Tokyo''s indie music scene.', '2-30-4 Kitazawa', 'Tokyo', 'Japan', 3, 125.00, '/placeholder.svg?height=400&width=600', ARRAY['Live Music', 'Bar', 'Free WiFi', 'Cafe']),
('Kasai Seaside Hotel', 'Family-friendly hotel near the aquarium.', '6-2-3 Kasai', 'Tokyo', 'Japan', 3, 105.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Parking', 'Kids Area']),
('Toranomon Hills Hotel', 'Ultra-luxury hotel in the new business hub.', '1-23-4 Toranomon', 'Tokyo', 'Japan', 5, 680.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Concierge', 'Free WiFi']),
('Koenji Art Hotel', 'Creative accommodation in the artistic district.', '4-28-1 Koenji-Minami', 'Tokyo', 'Japan', 3, 90.00, '/placeholder.svg?height=400&width=600', ARRAY['Art Gallery', 'Cafe', 'Free WiFi']),
('Ochanomizu Student Hotel', 'Budget-friendly near universities.', '2-3-4 Kanda-Surugadai', 'Tokyo', 'Japan', 2, 65.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Shared Kitchen', 'Study Room']),
('Ariake Sports Hotel', 'Modern hotel near Olympic venues.', '3-7-1 Ariake', 'Tokyo', 'Japan', 4, 230.00, '/placeholder.svg?height=400&width=600', ARRAY['Gym', 'Restaurant', 'Free WiFi', 'Sports Facilities']),
('Hiroo Embassy Hotel', 'Quiet luxury near embassies and parks.', '5-6-6 Hiroo', 'Tokyo', 'Japan', 4, 340.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Garden', 'Free WiFi', 'Concierge']),
('Sangenjaya Local Hotel', 'Authentic neighborhood experience.', '2-15-1 Sangenjaya', 'Tokyo', 'Japan', 3, 95.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Restaurant', 'Bar']),
('Haneda Airport Hotel', 'Convenient transit hotel near the airport.', '3-3-2 Haneda', 'Tokyo', 'Japan', 4, 200.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Airport Shuttle', '24h Reception']),
('Jiyugaoka Garden Hotel', 'Charming hotel in a trendy residential area.', '2-11-3 Jiyugaoka', 'Tokyo', 'Japan', 4, 260.00, '/placeholder.svg?height=400&width=600', ARRAY['Cafe', 'Garden', 'Free WiFi', 'Bakery']),
('Kinshicho Business Hotel', 'Affordable option in East Tokyo.', '4-27-14 Kinshi', 'Tokyo', 'Japan', 3, 85.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Restaurant', 'Parking']),
('Takadanobaba Youth Hotel', 'Vibrant hotel popular with young travelers.', '1-35-3 Takadanobaba', 'Tokyo', 'Japan', 2, 55.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Shared Lounge', 'Kitchen']),
('Nihombashi Mitsui Hotel', 'Refined elegance in a historic building.', '2-1-1 Nihonbashi-Muromachi', 'Tokyo', 'Japan', 5, 540.00, '/placeholder.svg?height=400&width=600', ARRAY['Spa', 'Restaurant', 'Bar', 'Gym', 'Free WiFi', 'Concierge']),
('Kichijoji Park Hotel', 'Near popular Inokashira Park.', '1-15-5 Kichijoji-Honcho', 'Tokyo', 'Japan', 3, 140.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Park View']),
('Omotesando Fashion Hotel', 'Trendy hotel on Tokyo''s Champs-Élysées.', '4-3-10 Jingumae', 'Tokyo', 'Japan', 4, 350.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Spa', 'Shopping Concierge']),
('Nezu Museum Hotel', 'Art-inspired hotel near the famous museum.', '6-5-36 Minami-Aoyama', 'Tokyo', 'Japan', 4, 320.00, '/placeholder.svg?height=400&width=600', ARRAY['Garden', 'Restaurant', 'Free WiFi', 'Art Tours']),
('Kamata Gateway Hotel', 'Easy access to both airports.', '5-13-1 Kamata', 'Tokyo', 'Japan', 3, 110.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Restaurant', 'Airport Access']),
('Chofu Suburban Hotel', 'Peaceful stay in residential West Tokyo.', '1-3-1 Chofu', 'Tokyo', 'Japan', 3, 95.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Parking', 'Restaurant']),
('Marunouchi Executive Hotel', 'Premium business hotel near Imperial Palace.', '2-4-1 Marunouchi', 'Tokyo', 'Japan', 5, 600.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Gym', 'Spa', 'Free WiFi', 'Business Center', 'Concierge']);

-- NEW YORK, USA (50 hotels)
INSERT INTO hotels (name, description, address, city, country, star_rating, price_per_night, main_image, amenities) VALUES
('Manhattan Skyline Hotel', 'Stunning views of the NYC skyline from every room.', '350 W 42nd Street', 'New York', 'United States', 5, 550.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Free WiFi', 'Concierge']),
('Times Square Central', 'In the heart of the action at Times Square.', '234 W 47th Street', 'New York', 'United States', 4, 380.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'City View']),
('Central Park View Hotel', 'Wake up to beautiful Central Park views.', '768 5th Avenue', 'New York', 'United States', 5, 720.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Park View', 'Gym', 'Free WiFi', 'Concierge']),
('SoHo Boutique Hotel', 'Artistic boutique hotel in trendy SoHo.', '125 Spring Street', 'New York', 'United States', 4, 420.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Art Gallery']),
('Brooklyn Bridge Hotel', 'Iconic views of Brooklyn Bridge and Manhattan.', '60 Furman Street', 'New York', 'United States', 4, 340.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Rooftop Terrace']),
('Midtown Business Hotel', 'Perfect for business travelers in Midtown.', '45 E 45th Street', 'New York', 'United States', 4, 320.00, '/placeholder.svg?height=400&width=600', ARRAY['Business Center', 'Restaurant', 'Gym', 'Free WiFi']),
('Greenwich Village Inn', 'Charming hotel in the historic Village.', '88 University Place', 'New York', 'United States', 3, 220.00, '/placeholder.svg?height=400&width=600', ARRAY['Cafe', 'Free WiFi', 'Garden']),
('Wall Street Executive Hotel', 'Luxury in the Financial District.', '55 Wall Street', 'New York', 'United States', 5, 480.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Gym', 'Spa', 'Free WiFi', 'Business Center']),
('Chelsea Art Hotel', 'Creative accommodations in Chelsea.', '222 W 23rd Street', 'New York', 'United States', 4, 290.00, '/placeholder.svg?height=400&width=600', ARRAY['Art Gallery', 'Restaurant', 'Bar', 'Free WiFi']),
('Upper East Side Luxury', 'Refined elegance on the Upper East Side.', '35 E 76th Street', 'New York', 'United States', 5, 650.00, '/placeholder.svg?height=400&width=600', ARRAY['Spa', 'Restaurant', 'Gym', 'Free WiFi', 'Concierge']),
('Harlem Renaissance Hotel', 'Cultural heritage in historic Harlem.', '2090 Adam Clayton Powell Jr Blvd', 'New York', 'United States', 4, 240.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Jazz Club', 'Free WiFi']),
('Lower East Side Hostel', 'Budget-friendly in the hip LES.', '168 Orchard Street', 'New York', 'United States', 2, 85.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Shared Kitchen', 'Lounge']),
('Fifth Avenue Grand', 'Prestigious address on Fifth Avenue.', '515 5th Avenue', 'New York', 'United States', 5, 800.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Multiple Restaurants', 'Bar', 'Gym', 'Concierge']),
('Williamsburg Hipster Hotel', 'Trendy accommodations in Brooklyn.', '96 Wythe Avenue', 'New York', 'United States', 4, 310.00, '/placeholder.svg?height=400&width=600', ARRAY['Rooftop Bar', 'Restaurant', 'Free WiFi', 'Pool']),
('Herald Square Hotel', 'Great location near Macy''s.', '19 W 31st Street', 'New York', 'United States', 3, 180.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Restaurant', '24h Reception']),
('East Village Boutique', 'Eclectic style in the East Village.', '25 Cooper Square', 'New York', 'United States', 3, 210.00, '/placeholder.svg?height=400&width=600', ARRAY['Bar', 'Cafe', 'Free WiFi']),
('Hudson Yards Modern Hotel', 'Ultra-modern hotel in the new Hudson Yards.', '20 Hudson Yards', 'New York', 'United States', 5, 580.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Free WiFi', 'Observation Deck Access']),
('Tribeca Loft Hotel', 'Spacious loft-style rooms in Tribeca.', '95 West Broadway', 'New York', 'United States', 4, 440.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Gym']),
('Battery Park Waterfront', 'Stunning harbor views near Lady Liberty.', '2 West Street', 'New York', 'United States', 4, 360.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Harbor View', 'Free WiFi', 'Gym']),
('NoHo Designer Hotel', 'Artistic luxury between SoHo and East Village.', '9 Crosby Street', 'New York', 'United States', 4, 400.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Design Interior']),
('Penn Station Hotel', 'Convenient location near Penn Station.', '401 7th Avenue', 'New York', 'United States', 3, 195.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', '24h Reception']),
('Flatiron District Hotel', 'Near the iconic Flatiron Building.', '11 E 24th Street', 'New York', 'United States', 4, 330.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Gym', 'Free WiFi', 'Rooftop']),
('Grand Central Hotel', 'Steps from Grand Central Terminal.', '109 E 42nd Street', 'New York', 'United States', 4, 350.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Business Center']),
('West Side Riverside Hotel', 'Peaceful location near Riverside Park.', '275 W 96th Street', 'New York', 'United States', 3, 230.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Park View', 'Free WiFi']),
('Meatpacking District Hotel', 'Stylish hotel in the vibrant Meatpacking.', '848 Washington Street', 'New York', 'United States', 4, 450.00, '/placeholder.svg?height=400&width=600', ARRAY['Rooftop Bar', 'Restaurant', 'Free WiFi', 'Club']),
('Lincoln Center Arts Hotel', 'Perfect for performing arts lovers.', '150 W 65th Street', 'New York', 'United States', 4, 380.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Theater Concierge']),
('Chinatown Budget Inn', 'Affordable stay in vibrant Chinatown.', '6 Mott Street', 'New York', 'United States', 2, 95.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Air Conditioning']),
('Murray Hill Residence Hotel', 'Extended stay comfort in Murray Hill.', '149 E 39th Street', 'New York', 'United States', 3, 260.00, '/placeholder.svg?height=400&width=600', ARRAY['Kitchenette', 'Free WiFi', 'Gym', 'Laundry']),
('High Line Hotel', 'Historic hotel near the High Line.', '180 10th Avenue', 'New York', 'United States', 4, 390.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Garden', 'Free WiFi', 'Coffee Shop']),
('Koreatown Modern Hotel', 'Contemporary stay in K-Town.', '6 W 32nd Street', 'New York', 'United States', 3, 175.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Spa', 'Free WiFi', 'Karaoke']),
('Gramercy Park Hotel', 'Exclusive access to private Gramercy Park.', '2 Lexington Avenue', 'New York', 'United States', 5, 520.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Gym', 'Park Access', 'Free WiFi']),
('Little Italy Charm Hotel', 'Authentic Italian neighborhood experience.', '134 Mulberry Street', 'New York', 'United States', 3, 190.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Cafe']),
('DUMBO Brooklyn Hotel', 'Artsy hotel under the Manhattan Bridge.', '30 Washington Street', 'New York', 'United States', 4, 370.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Rooftop', 'Free WiFi', 'Art Gallery']),
('Empire State Building View', 'Rooms with Empire State Building views.', '70 W 36th Street', 'New York', 'United States', 4, 340.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'City View', 'Free WiFi']),
('Columbia University Hotel', 'Near prestigious Columbia University.', '2920 Broadway', 'New York', 'United States', 3, 220.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Study Lounge']),
('Theater District Hotel', 'Walking distance to Broadway shows.', '226 W 52nd Street', 'New York', 'United States', 4, 410.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Theater Tickets']),
('Roosevelt Island Hotel', 'Unique island escape in the East River.', '455 Main Street', 'New York', 'United States', 3, 200.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'River View', 'Tram Access']),
('Union Square Hotel', 'Prime location at Union Square.', '201 Park Avenue South', 'New York', 'United States', 4, 355.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Gym', 'Free WiFi', 'Rooftop']),
('Astoria Queens Hotel', 'Affordable comfort in diverse Queens.', '36-05 30th Avenue', 'New York', 'United States', 3, 140.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Parking']),
('NoMad Luxury Hotel', 'Sophisticated elegance in NoMad.', '1170 Broadway', 'New York', 'United States', 5, 490.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Gym', 'Spa', 'Free WiFi', 'Library']),
('Coney Island Beach Hotel', 'Summer fun at Coney Island.', '1000 Surf Avenue', 'New York', 'United States', 3, 160.00, '/placeholder.svg?height=400&width=600', ARRAY['Beach Access', 'Restaurant', 'Free WiFi', 'Ocean View']),
('Madison Avenue Hotel', 'Upscale shopping district location.', '83 Madison Avenue', 'New York', 'United States', 4, 420.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Gym', 'Free WiFi', 'Shopping Concierge']),
('Bronx Zoo Area Hotel', 'Family-friendly near the Bronx Zoo.', '2515 Southern Boulevard', 'New York', 'United States', 3, 135.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Parking', 'Kids Activities']),
('Staten Island Ferry Hotel', 'Near the free Staten Island Ferry.', '4 South Street', 'New York', 'United States', 3, 175.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Harbor View', 'Free WiFi']),
('Central Park South Hotel', 'Premium location on Central Park South.', '160 Central Park South', 'New York', 'United States', 5, 750.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Park View', 'Concierge']),
('Bowery Historic Hotel', 'Character-filled hotel on the Bowery.', '335 Bowery', 'New York', 'United States', 3, 240.00, '/placeholder.svg?height=400&width=600', ARRAY['Bar', 'Restaurant', 'Free WiFi', 'Live Music']),
('World Trade Center Hotel', 'Modern hotel near the 9/11 Memorial.', '133 Greenwich Street', 'New York', 'United States', 4, 380.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Gym', 'Free WiFi', 'Memorial View']),
('Rockefeller Center Hotel', 'Steps from Rockefeller Center.', '45 Rockefeller Plaza', 'New York', 'United States', 5, 560.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Spa', 'Gym', 'Free WiFi', 'Ice Rink Access']),
('Park Slope Brooklyn Hotel', 'Family-friendly in charming Park Slope.', '282 5th Avenue', 'New York', 'United States', 3, 210.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Garden', 'Free WiFi', 'Kids Welcome']);

-- PARIS, FRANCE (50 hotels)
INSERT INTO hotels (name, description, address, city, country, star_rating, price_per_night, main_image, amenities) VALUES
('Eiffel Tower View Hotel', 'Romantic hotel with stunning Eiffel Tower views.', '17 Avenue de Suffren', 'Paris', 'France', 5, 650.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Spa', 'Tower View', 'Free WiFi', 'Concierge']),
('Champs-Élysées Palace', 'Luxurious hotel on the famous avenue.', '112 Avenue des Champs-Élysées', 'Paris', 'France', 5, 780.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Free WiFi', 'Concierge']),
('Le Marais Boutique Hotel', 'Charming boutique in the historic Marais.', '20 Rue des Archives', 'Paris', 'France', 4, 320.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Courtyard']),
('Montmartre Artist Hotel', 'Bohemian charm near Sacré-Cœur.', '78 Rue Lepic', 'Paris', 'France', 3, 180.00, '/placeholder.svg?height=400&width=600', ARRAY['Cafe', 'Free WiFi', 'Art Gallery']),
('Saint-Germain-des-Prés Hotel', 'Intellectual Left Bank elegance.', '42 Rue Bonaparte', 'Paris', 'France', 4, 420.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Library', 'Free WiFi']),
('Louvre District Hotel', 'Steps from the world''s greatest museum.', '5 Rue de Rivoli', 'Paris', 'France', 4, 380.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Museum Tours']),
('Opera Quarter Grand Hotel', 'Elegant hotel near Palais Garnier.', '8 Rue Scribe', 'Paris', 'France', 5, 520.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Spa', 'Free WiFi', 'Theater Concierge']),
('Latin Quarter Student Inn', 'Budget-friendly in the university district.', '31 Rue des Écoles', 'Paris', 'France', 2, 95.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Cafe', 'Study Area']),
('Bastille Modern Hotel', 'Contemporary design near Place de la Bastille.', '12 Boulevard Beaumarchais', 'Paris', 'France', 4, 290.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Gym', 'Free WiFi']),
('Arc de Triomphe View Hotel', 'Spectacular views of the monument.', '1 Avenue de la Grande Armée', 'Paris', 'France', 5, 580.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Spa', 'Monument View', 'Free WiFi']),
('Canal Saint-Martin Hotel', 'Trendy hotel on the picturesque canal.', '5 Quai de Valmy', 'Paris', 'France', 3, 210.00, '/placeholder.svg?height=400&width=600', ARRAY['Cafe', 'Bar', 'Free WiFi', 'Canal View']),
('Pigalle Nightlife Hotel', 'Vibrant hotel in the entertainment district.', '25 Rue Fontaine', 'Paris', 'France', 3, 175.00, '/placeholder.svg?height=400&width=600', ARRAY['Bar', 'Free WiFi', 'Nightclub']),
('Île de la Cité Hotel', 'Historic island location near Notre-Dame.', '19 Quai aux Fleurs', 'Paris', 'France', 4, 450.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Seine View', 'Free WiFi', 'Historic Tours']),
('Belleville Hip Hotel', 'Multicultural neighborhood experience.', '96 Rue de Belleville', 'Paris', 'France', 3, 140.00, '/placeholder.svg?height=400&width=600', ARRAY['Cafe', 'Bar', 'Free WiFi', 'Terrace']),
('Place Vendôme Luxury', 'Ultimate luxury near famous jewelers.', '15 Place Vendôme', 'Paris', 'France', 5, 950.00, '/placeholder.svg?height=400&width=600', ARRAY['Spa', 'Restaurant', 'Bar', 'Concierge', 'Free WiFi', 'Butler Service']),
('Oberkampf Trendy Hotel', 'Cool hotel in the hipster district.', '40 Rue Oberkampf', 'Paris', 'France', 3, 160.00, '/placeholder.svg?height=400&width=600', ARRAY['Bar', 'Cafe', 'Free WiFi', 'Rooftop']),
('Invalides Quarter Hotel', 'Near Napoleon''s tomb and Army Museum.', '29 Rue Cler', 'Paris', 'France', 4, 340.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Garden']),
('République Central Hotel', 'Well-connected location at Place de la République.', '3 Place de la République', 'Paris', 'France', 3, 195.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi']),
('Trocadéro Eiffel Hotel', 'Another perspective of the Iron Lady.', '6 Place du Trocadéro', 'Paris', 'France', 4, 480.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Terrace', 'Tower View', 'Free WiFi']),
('Gare du Nord Transit Hotel', 'Perfect for Eurostar travelers.', '18 Rue de Dunkerque', 'Paris', 'France', 3, 150.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', '24h Reception']),
('Palais Royal Garden Hotel', 'Overlooking the beautiful palace gardens.', '7 Rue de Beaujolais', 'Paris', 'France', 4, 420.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Garden View', 'Free WiFi', 'Concierge']),
('Père Lachaise Historic Inn', 'Near the famous cemetery.', '71 Rue de la Roquette', 'Paris', 'France', 3, 130.00, '/placeholder.svg?height=400&width=600', ARRAY['Cafe', 'Free WiFi', 'Historic Tours']),
('La Défense Business Hotel', 'Modern hotel in the business district.', '2 Place de La Défense', 'Paris', 'France', 4, 280.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Business Center', 'Gym', 'Free WiFi']),
('Sacré-Cœur View Hotel', 'Panoramic views from Montmartre heights.', '1 Rue Azaïs', 'Paris', 'France', 4, 350.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Terrace', 'City View', 'Free WiFi']),
('Luxembourg Gardens Hotel', 'Near the beautiful Luxembourg Gardens.', '17 Rue de Vaugirard', 'Paris', 'France', 4, 380.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Garden Access', 'Free WiFi', 'Library']),
('Musée d''Orsay Hotel', 'Art lovers'' paradise near the museum.', '1 Rue de la Légion d''Honneur', 'Paris', 'France', 4, 410.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Art Concierge']),
('Bercy Village Hotel', 'Modern area with wine warehouse charm.', '28 Cour Saint-Émilion', 'Paris', 'France', 3, 185.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Wine Tastings']),
('Batignolles Local Hotel', 'Authentic Parisian neighborhood.', '50 Rue des Batignolles', 'Paris', 'France', 3, 155.00, '/placeholder.svg?height=400&width=600', ARRAY['Cafe', 'Free WiFi', 'Garden']),
('Rue Mouffetard Inn', 'Charming market street location.', '116 Rue Mouffetard', 'Paris', 'France', 2, 110.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Breakfast', 'Market Access']),
('Concorde Plaza Hotel', 'Prestigious Place de la Concorde address.', '2 Place de la Concorde', 'Paris', 'France', 5, 720.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Free WiFi', 'Concierge']),
('Buttes-Chaumont Park Hotel', 'Near the stunning hilltop park.', '2 Rue Manin', 'Paris', 'France', 3, 145.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Park View']),
('Avenue Montaigne Fashion Hotel', 'Haute couture shopping destination.', '25 Avenue Montaigne', 'Paris', 'France', 5, 850.00, '/placeholder.svg?height=400&width=600', ARRAY['Spa', 'Restaurant', 'Bar', 'Personal Shopper', 'Free WiFi']),
('Grands Boulevards Hotel', 'Historic grand boulevard location.', '38 Boulevard des Capucines', 'Paris', 'France', 4, 310.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Theater District']),
('Menilmontant Creative Hotel', 'Artistic neighborhood vibe.', '15 Rue Boyer', 'Paris', 'France', 3, 125.00, '/placeholder.svg?height=400&width=600', ARRAY['Cafe', 'Free WiFi', 'Art Studio']),
('Haussmann Boulevard Hotel', 'Classic Haussmannian architecture.', '88 Boulevard Haussmann', 'Paris', 'France', 4, 360.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Classic Decor']),
('Nation Square Hotel', 'Convenient metro access at Place de la Nation.', '5 Place de la Nation', 'Paris', 'France', 3, 170.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Metro Access']),
('Bois de Boulogne Hotel', 'Near Paris''s largest park.', '2 Route de Suresnes', 'Paris', 'France', 4, 290.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Park Access', 'Free WiFi', 'Bike Rental']),
('Sentier Tech Hotel', 'Modern hotel in the startup district.', '45 Rue du Sentier', 'Paris', 'France', 3, 200.00, '/placeholder.svg?height=400&width=600', ARRAY['Coworking Space', 'Cafe', 'Free WiFi']),
('Arts et Métiers Hotel', 'Near the fascinating science museum.', '20 Rue Réaumur', 'Paris', 'France', 3, 185.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Museum Access']),
('Château de Vincennes Hotel', 'Near the medieval fortress.', '1 Avenue de Paris', 'Paris', 'France', 3, 135.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Castle Tours']),
('Seine River Cruise Hotel', 'Floating hotel on the Seine.', 'Port de Javel', 'Paris', 'France', 4, 440.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'River View', 'Free WiFi', 'Cruise']),
('Panthéon Quarter Hotel', 'Near the neoclassical mausoleum.', '9 Rue Soufflot', 'Paris', 'France', 4, 330.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Historic View']),
('Bourse Financial Hotel', 'Business district elegance.', '16 Rue Vivienne', 'Paris', 'France', 4, 350.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Business Center', 'Free WiFi']),
('Clignancourt Market Hotel', 'Near Europe''s largest flea market.', '110 Rue des Rosiers', 'Paris', 'France', 2, 85.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Market Access', 'Breakfast']),
('Parc Monceau Hotel', 'Charming park neighborhood.', '48 Boulevard de Courcelles', 'Paris', 'France', 4, 375.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Garden', 'Free WiFi']),
('Moulin Rouge District Hotel', 'Entertainment district excitement.', '82 Boulevard de Clichy', 'Paris', 'France', 3, 195.00, '/placeholder.svg?height=400&width=600', ARRAY['Bar', 'Free WiFi', 'Show Tickets']),
('Versailles Gateway Hotel', 'Easy access to the palace.', '2 Rue de Vergennes', 'Paris', 'France', 3, 165.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Palace Tours']),
('Pompidou Center Hotel', 'Modern art lovers'' base.', '19 Rue Beaubourg', 'Paris', 'France', 4, 340.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Art Tours']),
('Saint-Martin Canal Barge', 'Unique houseboat accommodation.', 'Quai de Jemmapes', 'Paris', 'France', 3, 220.00, '/placeholder.svg?height=400&width=600', ARRAY['Kitchenette', 'Canal View', 'Free WiFi']);

-- BALI, INDONESIA (50 hotels)
INSERT INTO hotels (name, description, address, city, country, star_rating, price_per_night, main_image, amenities) VALUES
('Ubud Rice Terrace Resort', 'Stunning views of iconic rice paddies.', 'Jl. Raya Tegallalang', 'Bali', 'Indonesia', 5, 380.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Rice Terrace View', 'Free WiFi', 'Yoga']),
('Seminyak Beach Club Hotel', 'Beachfront luxury with vibrant nightlife.', 'Jl. Kayu Aya', 'Bali', 'Indonesia', 5, 420.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Beach Club', 'Restaurant', 'Bar', 'Spa', 'Free WiFi']),
('Kuta Surfer Lodge', 'Budget-friendly for wave riders.', 'Jl. Pantai Kuta', 'Bali', 'Indonesia', 3, 65.00, '/placeholder.svg?height=400&width=600', ARRAY['Surf Storage', 'Restaurant', 'Free WiFi', 'Beach Access']),
('Nusa Dua Luxury Resort', 'Premium beachfront escape.', 'Kawasan BTDC', 'Bali', 'Indonesia', 5, 550.00, '/placeholder.svg?height=400&width=600', ARRAY['Private Beach', 'Pool', 'Spa', 'Golf', 'Multiple Restaurants', 'Free WiFi']),
('Canggu Hipster Hotel', 'Trendy stay near echo beach.', 'Jl. Pantai Batu Bolong', 'Bali', 'Indonesia', 4, 180.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Restaurant', 'Bar', 'Surf Rental', 'Free WiFi']),
('Sanur Peaceful Resort', 'Traditional Balinese tranquility.', 'Jl. Danau Tamblingan', 'Bali', 'Indonesia', 4, 220.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Beach Access', 'Restaurant', 'Free WiFi']),
('Uluwatu Cliff Villa', 'Dramatic clifftop accommodations.', 'Jl. Labuan Sait', 'Bali', 'Indonesia', 5, 480.00, '/placeholder.svg?height=400&width=600', ARRAY['Private Pool', 'Ocean View', 'Restaurant', 'Spa', 'Free WiFi']),
('Jimbaran Bay Resort', 'Famous sunset seafood dining location.', 'Jl. Pantai Jimbaran', 'Bali', 'Indonesia', 4, 320.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Beach Access', 'Seafood Restaurant', 'Spa', 'Free WiFi']),
('Ubud Jungle Retreat', 'Eco-lodge in the tropical forest.', 'Jl. Monkey Forest', 'Bali', 'Indonesia', 4, 250.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Yoga Studio', 'Restaurant', 'Free WiFi']),
('Legian Beach Hotel', 'Classic beachfront location.', 'Jl. Pantai Legian', 'Bali', 'Indonesia', 4, 190.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Beach Access', 'Restaurant', 'Bar', 'Free WiFi']),
('Tanah Lot View Resort', 'Views of the iconic sea temple.', 'Jl. Tanah Lot', 'Bali', 'Indonesia', 4, 280.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Restaurant', 'Temple View', 'Spa', 'Free WiFi']),
('Amed Diving Resort', 'Scuba paradise on the east coast.', 'Jl. Amed', 'Bali', 'Indonesia', 3, 95.00, '/placeholder.svg?height=400&width=600', ARRAY['Dive Center', 'Pool', 'Restaurant', 'Free WiFi', 'Beach']),
('Lovina Dolphin Hotel', 'Famous for dolphin watching.', 'Jl. Raya Lovina', 'Bali', 'Indonesia', 3, 80.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Restaurant', 'Dolphin Tours', 'Free WiFi']),
('Bedugul Mountain Resort', 'Cool mountain retreat.', 'Jl. Raya Bedugul', 'Bali', 'Indonesia', 4, 200.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Restaurant', 'Garden', 'Mountain View', 'Free WiFi']),
('Munduk Waterfall Lodge', 'Near stunning waterfalls.', 'Jl. Raya Munduk', 'Bali', 'Indonesia', 3, 110.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Garden', 'Waterfall Tours', 'Free WiFi']),
('Kerobokan Villas', 'Private villa compound.', 'Jl. Raya Kerobokan', 'Bali', 'Indonesia', 5, 350.00, '/placeholder.svg?height=400&width=600', ARRAY['Private Pool', 'Kitchen', 'Butler', 'Free WiFi']),
('Tabanan Eco Resort', 'Sustainable rice field retreat.', 'Jl. Subak Tabanan', 'Bali', 'Indonesia', 4, 240.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Organic Restaurant', 'Rice Fields', 'Yoga', 'Free WiFi']),
('Padang Padang Beach Inn', 'Near the famous surf break.', 'Jl. Labuan Sait', 'Bali', 'Indonesia', 3, 75.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Beach Access', 'Surf Rental', 'Free WiFi']),
('Denpasar City Hotel', 'Central Bali base.', 'Jl. Diponegoro', 'Bali', 'Indonesia', 3, 55.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Parking', 'City Tours']),
('Tirta Gangga Palace Hotel', 'Near the water palace.', 'Jl. Tirta Gangga', 'Bali', 'Indonesia', 4, 180.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Restaurant', 'Garden', 'Palace Tours', 'Free WiFi']),
('Candidasa Bay Resort', 'Quiet east coast escape.', 'Jl. Raya Candidasa', 'Bali', 'Indonesia', 4, 160.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Beach Access', 'Restaurant', 'Spa', 'Free WiFi']),
('Tegallalang Art Village Hotel', 'Near artisan workshops.', 'Jl. Raya Tegallalang', 'Bali', 'Indonesia', 3, 90.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Art Tours', 'Garden']),
('Pemuteran Reef Resort', 'Coral restoration paradise.', 'Jl. Raya Pemuteran', 'Bali', 'Indonesia', 4, 210.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Dive Center', 'Restaurant', 'Beach', 'Free WiFi']),
('Ubud Sacred Monkey Hotel', 'Near the monkey forest sanctuary.', 'Jl. Monkey Forest', 'Bali', 'Indonesia', 3, 120.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Restaurant', 'Garden', 'Free WiFi']),
('Bingin Surf Camp', 'Hardcore surfer accommodation.', 'Jl. Pantai Bingin', 'Bali', 'Indonesia', 2, 45.00, '/placeholder.svg?height=400&width=600', ARRAY['Surf Rental', 'Restaurant', 'Free WiFi', 'Beach']),
('Sidemen Valley Resort', 'Authentic Balinese countryside.', 'Jl. Raya Sidemen', 'Bali', 'Indonesia', 4, 195.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Restaurant', 'Rice Terrace View', 'Spa', 'Free WiFi']),
('Echo Beach Boutique Hotel', 'Trendy surfer hangout.', 'Jl. Pantai Batu Mejan', 'Bali', 'Indonesia', 4, 170.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Beach Club', 'Restaurant', 'Bar', 'Free WiFi']),
('Balangan Cliff Resort', 'Hidden gem on the Bukit.', 'Jl. Pantai Balangan', 'Bali', 'Indonesia', 4, 230.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Ocean View', 'Restaurant', 'Spa', 'Free WiFi']),
('Tulamben Dive Lodge', 'USAT Liberty wreck diving.', 'Jl. Raya Tulamben', 'Bali', 'Indonesia', 3, 85.00, '/placeholder.svg?height=400&width=600', ARRAY['Dive Center', 'Restaurant', 'Beach', 'Free WiFi']),
('Ubud Art Market Hotel', 'Central Ubud location.', 'Jl. Raya Ubud', 'Bali', 'Indonesia', 3, 100.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Art Gallery', 'Spa']),
('Menjangan Island Resort', 'Near pristine diving.', 'Jl. Raya Menjangan', 'Bali', 'Indonesia', 4, 250.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Dive Center', 'Restaurant', 'Nature Tours', 'Free WiFi']),
('Pecatu Luxury Villas', 'Exclusive clifftop privacy.', 'Jl. Pecatu Indah', 'Bali', 'Indonesia', 5, 520.00, '/placeholder.svg?height=400&width=600', ARRAY['Private Pool', 'Ocean View', 'Butler', 'Spa', 'Free WiFi']),
('Kintamani Volcano View', 'Mount Batur panoramas.', 'Jl. Raya Penelokan', 'Bali', 'Indonesia', 4, 175.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Volcano View', 'Trekking Tours', 'Free WiFi']),
('Gianyar Cultural Hotel', 'Near traditional villages.', 'Jl. Raya Gianyar', 'Bali', 'Indonesia', 3, 70.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Cultural Tours']),
('Pererenan Beach Resort', 'Quiet alternative to Seminyak.', 'Jl. Pantai Pererenan', 'Bali', 'Indonesia', 4, 200.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Beach Access', 'Restaurant', 'Yoga', 'Free WiFi']),
('Sekumpul Waterfall Lodge', 'Near Bali''s most beautiful waterfall.', 'Jl. Raya Sekumpul', 'Bali', 'Indonesia', 3, 95.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Waterfall Tours', 'Garden', 'Free WiFi']),
('Tegunungan Cascade Hotel', 'Waterfall lovers'' base.', 'Jl. Ir. Sutami', 'Bali', 'Indonesia', 3, 85.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Restaurant', 'Waterfall Access', 'Free WiFi']),
('Soka Beach Resort', 'Secluded black sand beach.', 'Jl. Raya Soka', 'Bali', 'Indonesia', 4, 165.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Beach Access', 'Restaurant', 'Spa', 'Free WiFi']),
('Penglipuran Village Inn', 'Traditional village experience.', 'Desa Penglipuran', 'Bali', 'Indonesia', 3, 75.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Cultural Tours', 'Garden', 'Free WiFi']),
('Ungasan Clifftop Resort', 'Stunning south coast views.', 'Jl. Melasti Ungasan', 'Bali', 'Indonesia', 5, 450.00, '/placeholder.svg?height=400&width=600', ARRAY['Private Pool', 'Spa', 'Restaurant', 'Ocean View', 'Free WiFi']),
('Pupuan Rice Terrace Hotel', 'Off-the-beaten-path terraces.', 'Jl. Raya Pupuan', 'Bali', 'Indonesia', 3, 105.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Rice Terrace View', 'Garden', 'Free WiFi']),
('Kedonganan Beach Hotel', 'Near the fish market.', 'Jl. Pantai Kedonganan', 'Bali', 'Indonesia', 3, 115.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Beach Access', 'Seafood', 'Free WiFi']),
('Mengwi Temple Hotel', 'Near Taman Ayun temple.', 'Jl. Raya Mengwi', 'Bali', 'Indonesia', 3, 80.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Temple Tours', 'Garden', 'Free WiFi']),
('Seseh Hidden Villa', 'Secret beach luxury.', 'Jl. Pantai Seseh', 'Bali', 'Indonesia', 4, 280.00, '/placeholder.svg?height=400&width=600', ARRAY['Private Pool', 'Beach Access', 'Restaurant', 'Spa', 'Free WiFi']),
('Bangli Mountain Lodge', 'Cool highlands escape.', 'Jl. Raya Bangli', 'Bali', 'Indonesia', 3, 70.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Mountain View', 'Garden', 'Free WiFi']),
('Nyang Nyang Beach Camp', 'Isolated beach paradise.', 'Jl. Nyang Nyang', 'Bali', 'Indonesia', 2, 50.00, '/placeholder.svg?height=400&width=600', ARRAY['Beach Access', 'Restaurant', 'Free WiFi']),
('Tampaksiring Palace Hotel', 'Near the presidential palace.', 'Jl. Raya Tampaksiring', 'Bali', 'Indonesia', 4, 185.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Restaurant', 'Temple Tours', 'Garden', 'Free WiFi']),
('Goa Gajah Heritage Inn', 'Near the elephant cave.', 'Jl. Goa Gajah', 'Bali', 'Indonesia', 3, 90.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Temple Tours', 'Garden', 'Free WiFi']),
('Sanur Sunrise Hotel', 'Famous east coast sunrises.', 'Jl. Pantai Sindhu', 'Bali', 'Indonesia', 4, 195.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Beach Access', 'Restaurant', 'Spa', 'Free WiFi']);

-- LONDON, UK (50 hotels)
INSERT INTO hotels (name, description, address, city, country, star_rating, price_per_night, main_image, amenities) VALUES
('Westminster Palace Hotel', 'Near Big Ben and Parliament.', '1 Victoria Street', 'London', 'United Kingdom', 5, 580.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Spa', 'Big Ben View', 'Free WiFi', 'Concierge']),
('Covent Garden Theatre Hotel', 'Heart of London''s West End.', '10 Monmouth Street', 'London', 'United Kingdom', 4, 380.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Theater Concierge']),
('Tower Bridge View Hotel', 'Iconic bridge panoramas.', '1 Tower Bridge Road', 'London', 'United Kingdom', 5, 520.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Bridge View', 'Spa', 'Free WiFi']),
('Kensington Royal Hotel', 'Elegant neighborhood near Hyde Park.', '25 Kensington High Street', 'London', 'United Kingdom', 5, 490.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Spa', 'Park Access', 'Free WiFi', 'Gym']),
('Shoreditch Hipster Hotel', 'Trendy East London base.', '100 Shoreditch High Street', 'London', 'United Kingdom', 4, 290.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Rooftop', 'Free WiFi']),
('Kings Cross Modern Hotel', 'Near St Pancras and Harry Potter.', '1 Pancras Road', 'London', 'United Kingdom', 4, 320.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Train Station Access']),
('Camden Market Hotel', 'Eclectic neighborhood experience.', '55 Camden High Street', 'London', 'United Kingdom', 3, 180.00, '/placeholder.svg?height=400&width=600', ARRAY['Bar', 'Free WiFi', 'Market Access', 'Live Music']),
('Mayfair Luxury Hotel', 'Prestigious West End address.', '45 Park Lane', 'London', 'United Kingdom', 5, 750.00, '/placeholder.svg?height=400&width=600', ARRAY['Pool', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Concierge', 'Free WiFi']),
('Notting Hill Boutique', 'Colorful houses and Portobello Market.', '22 Pembridge Gardens', 'London', 'United Kingdom', 4, 340.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Garden', 'Free WiFi']),
('South Bank Arts Hotel', 'Near Tate Modern and Globe Theatre.', '20 Upper Ground', 'London', 'United Kingdom', 4, 360.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'River View', 'Free WiFi']),
('Greenwich Maritime Hotel', 'Historic maritime London.', '5 College Approach', 'London', 'United Kingdom', 4, 280.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Historic Tours', 'Park Access']),
('Piccadilly Circus Hotel', 'Central London landmark.', '3 Piccadilly', 'London', 'United Kingdom', 4, 420.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'City View']),
('Brick Lane Budget Hotel', 'Curry mile and street art.', '91 Brick Lane', 'London', 'United Kingdom', 2, 95.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Restaurant Access']),
('Chelsea Garden Hotel', 'Refined residential area.', '15 Sloane Street', 'London', 'United Kingdom', 5, 550.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Garden', 'Spa', 'Free WiFi']),
('Bloomsbury Literary Hotel', 'Near British Museum and bookshops.', '45 Great Russell Street', 'London', 'United Kingdom', 4, 310.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Library', 'Free WiFi', 'Museum Tours']),
('Canary Wharf Business Hotel', 'Financial district convenience.', '25 Canada Square', 'London', 'United Kingdom', 4, 280.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Gym', 'Business Center', 'Free WiFi']),
('Hyde Park Corner Hotel', 'Premium park location.', '1 Hyde Park Corner', 'London', 'United Kingdom', 5, 620.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Spa', 'Park View', 'Gym', 'Free WiFi']),
('Soho Central Hotel', 'Nightlife and entertainment hub.', '12 Dean Street', 'London', 'United Kingdom', 4, 380.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Club Access']),
('Brixton Cultural Hotel', 'Vibrant South London.', '389 Coldharbour Lane', 'London', 'United Kingdom', 3, 150.00, '/placeholder.svg?height=400&width=600', ARRAY['Bar', 'Free WiFi', 'Live Music']),
('Hampstead Village Inn', 'Charming North London village.', '2 Flask Walk', 'London', 'United Kingdom', 4, 290.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Garden', 'Free WiFi', 'Heath Access']),
('Oxford Street Shopping Hotel', 'Shoppers'' paradise.', '200 Oxford Street', 'London', 'United Kingdom', 4, 350.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Shopping Concierge']),
('Borough Market Hotel', 'Foodie heaven location.', '8 Southwark Street', 'London', 'United Kingdom', 4, 330.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Market Access']),
('Victoria Station Hotel', 'Major transport hub.', '101 Buckingham Palace Road', 'London', 'United Kingdom', 3, 200.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', '24h Reception']),
('Marylebone Village Hotel', 'Upscale village atmosphere.', '35 Marylebone High Street', 'London', 'United Kingdom', 4, 370.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Spa', 'Free WiFi']),
('Stratford Olympic Hotel', 'Near Queen Elizabeth Park.', '1 Westfield Avenue', 'London', 'United Kingdom', 4, 220.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Gym', 'Free WiFi', 'Park Access']),
('Islington Angel Hotel', 'Trendy North London.', '10 Upper Street', 'London', 'United Kingdom', 3, 190.00, '/placeholder.svg?height=400&width=600', ARRAY['Bar', 'Restaurant', 'Free WiFi']),
('St. Paul''s Cathedral View', 'Iconic dome panoramas.', '5 Ludgate Hill', 'London', 'United Kingdom', 4, 400.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Cathedral View', 'Free WiFi']),
('Paddington Bear Hotel', 'Near the famous station.', '2 Praed Street', 'London', 'United Kingdom', 3, 175.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Heathrow Express']),
('Battersea Park Hotel', 'South London park retreat.', '15 Prince of Wales Drive', 'London', 'United Kingdom', 4, 260.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Park View', 'Free WiFi', 'Gym']),
('Hoxton Square Hotel', 'Creative East London.', '81 Hoxton Square', 'London', 'United Kingdom', 4, 300.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Art Gallery']),
('Leicester Square Entertainment', 'Movie premieres and shows.', '5 Leicester Square', 'London', 'United Kingdom', 4, 390.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Cinema Access']),
('Fulham Riverside Hotel', 'Thames-side location.', '2 Fulham Broadway', 'London', 'United Kingdom', 3, 185.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'River View', 'Free WiFi']),
('Knightsbridge Luxury Hotel', 'Near Harrods department store.', '10 Knightsbridge', 'London', 'United Kingdom', 5, 680.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Spa', 'Shopping Concierge', 'Free WiFi']),
('Wimbledon Tennis Hotel', 'Sports lover''s choice.', '20 Church Road', 'London', 'United Kingdom', 4, 270.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Tennis Courts', 'Gym']),
('Richmond Park Hotel', 'Near royal deer park.', '1 Richmond Green', 'London', 'United Kingdom', 4, 250.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Garden', 'Park Access', 'Free WiFi']),
('East End Market Hotel', 'Authentic London experience.', '50 Mile End Road', 'London', 'United Kingdom', 2, 85.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Breakfast']),
('Bond Street Fashion Hotel', 'Designer shopping destination.', '35 New Bond Street', 'London', 'United Kingdom', 5, 600.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Personal Shopper', 'Spa', 'Free WiFi']),
('Waterloo Station Hotel', 'South Bank transport hub.', '8 York Road', 'London', 'United Kingdom', 3, 195.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Train Access']),
('Dalston Creative Hotel', 'Artistic East London.', '100 Kingsland Road', 'London', 'United Kingdom', 3, 160.00, '/placeholder.svg?height=400&width=600', ARRAY['Bar', 'Free WiFi', 'Live Music']),
('Regent''s Park Hotel', 'Near beautiful royal park.', '2 Park Road', 'London', 'United Kingdom', 4, 340.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Garden', 'Park Access', 'Free WiFi']),
('Clapham South Hotel', 'Young professionals'' area.', '70 Clapham High Street', 'London', 'United Kingdom', 3, 145.00, '/placeholder.svg?height=400&width=600', ARRAY['Bar', 'Restaurant', 'Free WiFi']),
('Barbican Arts Hotel', 'Near the cultural center.', '5 Silk Street', 'London', 'United Kingdom', 4, 320.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Arts Access']),
('Earls Court Budget Hotel', 'Affordable West London.', '25 Earls Court Road', 'London', 'United Kingdom', 2, 95.00, '/placeholder.svg?height=400&width=600', ARRAY['Free WiFi', 'Breakfast']),
('Fleet Street Press Hotel', 'Historic newspaper district.', '85 Fleet Street', 'London', 'United Kingdom', 4, 310.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Free WiFi', 'Library']),
('Heathrow Airport Hotel', 'Convenient for flights.', '234 Bath Road', 'London', 'United Kingdom', 4, 180.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Airport Shuttle', '24h Reception']),
('Crystal Palace Hotel', 'South London landmark area.', '20 Crystal Palace Park Road', 'London', 'United Kingdom', 3, 130.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Park View']),
('Whitechapel Historic Hotel', 'Jack the Ripper walking tours.', '90 Whitechapel Road', 'London', 'United Kingdom', 3, 140.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Free WiFi', 'Historic Tours']),
('Hackney Wick Arts Hotel', 'Creative warehouse district.', '15 White Post Lane', 'London', 'United Kingdom', 3, 165.00, '/placeholder.svg?height=400&width=600', ARRAY['Bar', 'Free WiFi', 'Art Studios']),
('Belgravia Grand Hotel', 'Exclusive embassy district.', '15 Belgrave Square', 'London', 'United Kingdom', 5, 700.00, '/placeholder.svg?height=400&width=600', ARRAY['Restaurant', 'Bar', 'Spa', 'Garden', 'Concierge', 'Free WiFi']);

-- Add room types for all new hotels
INSERT INTO room_types (hotel_id, name, description, max_guests, price_per_night, amenities, image_url, available_rooms)
SELECT 
  h.id,
  'Standard Room',
  'Comfortable room with all essential amenities for a pleasant stay.',
  2,
  h.price_per_night,
  ARRAY['King Bed', 'TV', 'Air Conditioning', 'Private Bathroom'],
  '/placeholder.svg?height=300&width=400',
  10
FROM hotels h
WHERE h.id NOT IN (SELECT DISTINCT hotel_id FROM room_types);

INSERT INTO room_types (hotel_id, name, description, max_guests, price_per_night, amenities, image_url, available_rooms)
SELECT 
  h.id,
  'Deluxe Room',
  'Spacious room with premium amenities and enhanced comfort.',
  3,
  h.price_per_night * 1.4,
  ARRAY['King Bed', 'Sofa', 'TV', 'Mini Bar', 'Air Conditioning', 'City View'],
  '/placeholder.svg?height=300&width=400',
  6
FROM hotels h
WHERE h.id NOT IN (SELECT DISTINCT hotel_id FROM room_types WHERE name = 'Deluxe Room');

INSERT INTO room_types (hotel_id, name, description, max_guests, price_per_night, amenities, image_url, available_rooms)
SELECT 
  h.id,
  'Suite',
  'Luxurious suite with separate living area and premium services.',
  4,
  h.price_per_night * 2,
  ARRAY['King Bed', 'Living Room', 'TV', 'Mini Bar', 'Jacuzzi', 'Premium View', 'Room Service'],
  '/placeholder.svg?height=300&width=400',
  3
FROM hotels h
WHERE h.id NOT IN (SELECT DISTINCT hotel_id FROM room_types WHERE name = 'Suite');

-- Add hotel images for all new hotels
INSERT INTO hotel_images (hotel_id, image_url, alt_text, display_order)
SELECT 
  h.id,
  '/placeholder.svg?height=400&width=600&query=' || REPLACE(LOWER(h.name), ' ', '-') || '-lobby',
  'Hotel Lobby',
  1
FROM hotels h
WHERE h.id NOT IN (SELECT DISTINCT hotel_id FROM hotel_images WHERE display_order = 1);

INSERT INTO hotel_images (hotel_id, image_url, alt_text, display_order)
SELECT 
  h.id,
  '/placeholder.svg?height=400&width=600&query=' || REPLACE(LOWER(h.name), ' ', '-') || '-pool',
  'Swimming Pool',
  2
FROM hotels h
WHERE h.id NOT IN (SELECT DISTINCT hotel_id FROM hotel_images WHERE display_order = 2);

INSERT INTO hotel_images (hotel_id, image_url, alt_text, display_order)
SELECT 
  h.id,
  '/placeholder.svg?height=400&width=600&query=' || REPLACE(LOWER(h.name), ' ', '-') || '-restaurant',
  'Restaurant',
  3
FROM hotels h
WHERE h.id NOT IN (SELECT DISTINCT hotel_id FROM hotel_images WHERE display_order = 3);
